# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_args": "00_utils.ipynb",
         "file_exists": "00_utils.ipynb",
         "get_ffp": "00_utils.ipynb",
         "get_gfp": "00_utils.ipynb",
         "get_likely_file_from_ftp": "00_utils.ipynb",
         "get_local_files": "00_utils.ipynb",
         "get_paras": "00_utils.ipynb",
         "fasta_file_pattern": "01_defaults.ipynb",
         "gtf_file_pattern": "01_defaults.ipynb",
         "ensembl_ftp": "01_defaults.ipynb",
         "species": "01_defaults.ipynb",
         "softwares": "01_defaults.ipynb",
         "defaults": "01_defaults.ipynb",
         "softwares_default": "01_defaults.ipynb",
         "task_get_file": "02_tasks.ipynb",
         "task_bwa_build_index": "02_tasks.ipynb",
         "task_bowtie_build_index": "02_tasks.ipynb",
         "task_bowtie2_build_index": "02_tasks.ipynb",
         "task_samtools_build_index": "02_tasks.ipynb",
         "task_hisat2_build_index": "02_tasks.ipynb",
         "task_picard_build_index": "02_tasks.ipynb",
         "task_build_rRNA_intervals": "02_tasks.ipynb",
         "task_extract_rRNA_bed": "02_tasks.ipynb",
         "task_gunzip": "02_tasks.ipynb",
         "cmd_wget": "03_commands.ipynb",
         "cmd_gunzip": "03_commands.ipynb",
         "cmd_mkdir": "03_commands.ipynb",
         "simple_reference": "04_pipelines.ipynb",
         "recipe": "05_recipes.ipynb"}

modules = ["utils.py",
           "defaults.py",
           "tasks.py",
           "commands.py",
           "pipelines.py",
           "recipes.py"]

doc_url = "https://btrspg.github.io/create_reference/"

git_url = "https://github.com/btrspg/create_reference/tree/master/"

def custom_doc_links(name): return None
