# AUTOGENERATED! DO NOT EDIT! File to edit: 03_commands.ipynb (unless otherwise specified).

__all__ = ['cmd_wget', 'cmd_gunzip']

# Cell

from .utils import file_exists

# Cell

def cmd_wget(link,filename):
    return 'wget -c {link} -O {filename}'.format(link=link,filename=filename)

def cmd_gunzip(filename):
    return 'gunzip -d {filename}'.format(filename)