# AUTOGENERATED! DO NOT EDIT! File to edit: 03_commands.ipynb (unless otherwise specified).

__all__ = ['cmd_wget', 'cmd_gunzip', 'cmd_mkdir']

# Cell

from .utils import file_exists

# Cell

def cmd_wget(link,filename):
    return 'wget -c {link} -O {filename}'.format(link=link,filename=filename)

def cmd_gunzip(filename):
    return 'gunzip -d {filename}'.format(filename)

def cmd_mkdir(*dirs):
    if len(dirs)==1 and dirs[0] == '':
        return 'echo No need to make dirs'
    else:
        return 'mkdir -p ' + ' '.join(dirs)