# AUTOGENERATED! DO NOT EDIT! File to edit: 05_recipes.ipynb (unless otherwise specified).

__all__ = ['recipe']

# Cell

from .tasks import *

# Cell

def recipe(workflow,species_paras):
    get_fasta = [
        workflow.add_task(
            func=task_get_file,
            params=dict(
                link=para['link_genome_fasta'],
                filename=para['local_genome_fasta'],
            ),
            uid='get_fasta_%s_%s' % (para['species'],para['version']) ,
            stage_name='get_fasta'
        ) for para in species_paras]

    get_gtf = [
        workflow.add_task(
            func=task_get_file,
            params=dict(
                link=para['link_transcriptome_gtf'],
                filename=para['local_transcriptome_gtf'],
            ),
            uid='get_gtf_%s_%s' % (para['species'],para['version']) ,
            stage_name='get_gtf'
        ) for para in species_paras]

