# AUTOGENERATED! DO NOT EDIT! File to edit: 02_tasks.ipynb (unless otherwise specified).

__all__ = ['task_get_file', 'task_bwa_build_index', 'task_bowtie_build_index', 'task_bowtie2_build_index',
           'task_gunzip']

# Cell
import os
from biocores.softwares.default import *
from biocores.softwares.bwa import Bwa
from biocores.softwares.bowtie import Bowtie
from biocores.softwares.bowtie2 import Bowtie2
from .commands import *
from .utils import file_exists

# Cell

def task_get_file(link,filename):
    if file_exists(filename):
        return 'echo {filename} exists'.format(filename=filename)
    else:
        cmds = [
            cmd_mkdir(os.path.dirname(filename)),
            cmd_wget(link,filename)
        ]
        return '\n'.join(cmds)

def task_bwa_build_index(software,reference):
    bwa = Bwa(software,bwaDefault)
    cmds = [
            bwa.cmd_build_index(reference)
        ]

    return '\n'.join(cmds)

def task_bowtie_build_index(software,reference, prefix):
    bowtie=Bowtie(software,bowtieDefault)
    cmds = [
            cmd_mkdir(os.path.dirname(prefix)),
            bowtie.cmd_build_index(reference, prefix)
        ]

    return '\n'.join(cmds)

def task_bowtie2_build_index(software,reference, prefix):
    bowtie2=Bowtie2(software,bowtie2Default)
    cmds = [
            cmd_mkdir(os.path.dirname(prefix)),
            bowtie2.cmd_build_index(reference, prefix)
        ]

    return '\n'.join(cmds)

def task_gunzip(gzipfile):
    return cmd_gunzip(gzipfile)