# AUTOGENERATED! DO NOT EDIT! File to edit: 00_utils.ipynb (unless otherwise specified).

__all__ = ['get_args', 'file_exists', 'get_ffp', 'get_gfp', 'get_likely_file_from_ftp']

# Cell
import os
import sys
import re
import argparse
import ftplib
from create_reference import defaults

# Cell
def get_args(*args):
    parser = argparse.ArgumentParser(prog='fetchr',
                                     description='Fetch and Generate references for bioinformatics analysis',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter
                                    )

    parser.add_argument('--species',nargs='+',choices=defaults.species,default='homo_spaiens',
                       help='Reference or references from which species')
    parser.add_argument('--indexs',nargs='+',choices=defaults.softwares,default='samtools',
                       help='Using which software(s) to create indexes')
    parser.add_argument('--reference-version','-rv',default=99,type=int,
                       help='For homo_spaiens, version=75 is the last version of Grch37 reference, \
                       you can check the version in ftp://ftp.ensembl.org/pub/')
    parser.add_argument('--outdir','-o',default='./',
                       help='Reference and indexes generated direction')
    parser.add_argument('--workflow','-w',default='sqlite:////sqlite.db',
                       help='Workflow path')
    parser.add_argument('--thread','-t',default=4,
                       help='Thread number')
    return parser.parse_args(args)


# Cell

def file_exists(f):
    return os.path.exists(f)

# Cell

def get_ffp(species):
    return re.compile(defaults.fasta_file_pattern.format(species=species),re.IGNORECASE)

def get_gfp(species):
    return re.compile(defaults.gtf_file_pattern.format(species=species),re.IGNORECASE)

# Cell

def get_likely_file_from_ftp(ftp,version,species,ftype,dtype,pattern):
    if ftype == 'fasta':
        direction='/pub/release-{version}/{ftype}/{species}/{dtype}/'.format(
            version=version,
            species=species,
            ftype=ftype,
            dtype=dtype)
    elif ftype == 'gtf':
        direction='/pub/release-{version}/{ftype}/{species}/'.format(
            version=version,
            species=species,
            ftype=ftype)
    try:

        ftp.cwd(direction)
        files = ftp.nlst()
        for f in files:
#                 print(f)
            if len(pattern.findall(f))>0:
                return 'ftp://'+ftp_server+direction+f
        raise ValueError('No fit ' + ftype +' file in ftp://'+ftp_server+direction)
    except ftplib.all_errors as e:
        print(e)
        sys.exit(1)
